version: '3.8'
services:
  redis:
    image: redis/redis-stack:latest
    container_name: redis-stack
    ports:
      - "6379:6379"
      - "8001:8001"
    networks:
      - app-network

  job-recommendation-system:
    build: .
    container_name: job-system
    ports:
      - "8080:8080"
    depends_on:
      - redis
    networks:
      - app-network
    environment:
      - SPRING_REDIS_HOST=redis
      - SPRING_REDIS_PORT=6379

networks:
  app-network:
    driver: bridge
