services:
  - type: web
    name: job-recommendation-backend
    env: docker
    repo: https://github.com/Tanishqvasani2906/Job_Recommendation_System_Backend
    branch: main
    region: frankfurt

    dockerfilePath: ./Dockerfile

    healthCheckPath: /actuator/health
    autoDeploy: true
